plugins:
  discourse_sms_authentication_enabled:
    default: false
    client: true
  discourse_sms_authentication_provider:
    client: false
    type: enum
    default: "Twilio"
    choices:
      - "Twilio"
  discourse_sms_authentication_account_sid:
    default: ""
    client: false
  discourse_sms_authentication_authtoken:
    default: ""
    client: false
  discourse_sms_authentication_send_phone:
    default: ""
    client: false
  discourse_sms_authentication_email_domain:
    default: ""
    client: true 
