plugins:
  discourse_sms_authentication_enabled:
    default: false
    client: true
  discourse_sms_authentication_provider:
    client: false
    type: enum
    default: "Twilio"
    choices:
      - "Twilio"
      - "Africa's Talking"
  discourse_sms_authentication_account_sid:
    default: ""
    client: false
  discourse_sms_authentication_authtoken:
    default: ""
    client: false
  discourse_sms_authentication_at_username:
    default: ""
    client: false
  discourse_sms_authentication_at_apikey:
    default: ""
    client: false
  discourse_sms_authentication_send_phone:
    default: ""
    client: false
  discourse_sms_authentication_email_domain:
    default: ""
    client: true
  discourse_sms_authentication_braze_api_key:
    default: ""
    client: false
  discourse_sms_authentication_braze_campaign_id:
    default: ""
    client: false
  discourse_sms_authentication_braze_url:
    default: ""
    client: false
